# Generated by Django 3.2.16 on 2025-06-23 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('type_work', models.CharField(choices=[('coursework', 'Курсовая'), ('diploma', 'Дипломная'), ('both', 'Курсовая + Дипломная')], max_length=10, verbose_name='Тип работы')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок сдачи')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='users.teacherprofile', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='StudentTopicChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_by_teacher', models.BooleanField(default=False, verbose_name='Подтверждено преподавателем')),
                ('chosen_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выбора')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_choice', to='users.studentprofile', verbose_name='Студент')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='topics.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Выбор темы студентом',
                'verbose_name_plural': 'Выборы тем студентами',
            },
        ),
    ]
