# Generated by Django 3.2.16 on 2025-06-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTopicChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_by_teacher', models.BooleanField(default=False)),
                ('chosen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('type_work', models.CharField(choices=[('coursework', 'Курсовая'), ('diploma', 'Дипломная'), ('both', 'Курсовая + Дипломная')], max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
