# Generated by Django 3.2.16 on 2025-06-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='studenttopicchoice',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_choice', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studenttopicchoice',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='topics.topic'),
        ),
    ]
