# Generated by Django 3.2.16 on 2025-06-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='deadline',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание темы'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='type_work',
            field=models.CharField(choices=[('coursework', 'Курсовая'), ('diploma', 'Дипломная'), ('both', 'Курсовая + Дипломная')], max_length=20, verbose_name='Тип работы'),
        ),
    ]
