# Generated by Django 3.2.16 on 2025-06-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20250627_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('waiting_student', 'ожидается студент'), ('waiting_confirmation', 'ожидает подтверждения'), ('confirmed', 'подтверждено')], default='waiting_student', max_length=32),
        ),
    ]
