# Generated by Django 3.2.16 on 2025-06-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
    ]
