# Generated by Django 3.2.16 on 2025-06-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250624_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='group_name',
            field=models.CharField(default='безгрупная мразь', max_length=100, verbose_name='Группа'),
        ),
    ]
