# Generated by Django 3.2.16 on 2025-06-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='title',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='academicDegree',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Ученая степень'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='academicTitle',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Ученое звание'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='jobTitle',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
