# Generated by Django 3.2.16 on 2025-06-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20250625_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='group_name',
            new_name='group',
        ),
    ]
